# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CodeWise Chronicles
email: pagaramol22@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to CodeWise Chronicles, where we explore the latest trends and innovations in technology, coding, and design. Dive into our insightful articles, tutorials, and resources to stay informed and inspired in the ever-evolving digital landscape.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: amolpagar
github_username:  amolpagar

# Minima theme settings
theme: minima
layout: page
permalink: /:title/

social_icons:
  email: your-email@example.com
  twitter: your_twitter_username
  github: your_github_username
  linkedin: your_linkedin_username
  facebook: your_facebook_username
  instagram: your_instagram_username
  youtube: your_youtube_channel
  pinterest: your_pinterest_username
  medium: your_medium_username
  rss: /feed.xml

# Dark theme settings
minima:
  skin: dark